

[tasks.internal-build-web]
private = true
env = { "RUSTFLAGS" = '--cfg getrandom_backend="wasm_js"' }
script = "cargo build --release --target wasm32-unknown-unknown --bin kg_web --features web"

[tasks.internal-clean-web]
private = true
script = "find 'web/kyles-game' -mindepth 1 -delete"

[tasks.internal-process-web]
private = true
script = "wasm-bindgen --out-dir web/kyles-game --out-name kg_wasm --target web target/wasm32-unknown-unknown/release/kg_web.wasm"

[tasks.build-web]
dependencies = ["internal-build-web", "internal-clean-web", "internal-process-web"]

[tasks.internal-run-web]
private = true
script = "basic-http-server web"

[tasks.run-web]
dependencies = ["build-web", "internal-run-web"]

[tasks.run-std]
script = "cargo run --bin kg_std --features std"