

[tasks.internal-build-web]
private = true
env = { "RUSTFLAGS" = '--cfg getrandom_backend="wasm_js"' }
script = "cargo build --release --target wasm32-unknown-unknown --features web --bin kg-std"

[tasks.internal-clean-web]
private = true
script = "find 'web/kyles-game' -mindepth 1 -delete"

[tasks.internal-process-web]
private = true
script = "wasm-bindgen --out-dir web/kyles-game --out-name kg-wasm --target web target/wasm32-unknown-unknown/release/kg-std.wasm"

[tasks.internal-optimize-web]
private = true
script = "wasm-opt -d -Oz -o web/kyles-game/kg-wasm_bg.wasm web/kyles-game/kg-wasm_bg.wasm"

[tasks.build-web]
dependencies = ["internal-build-web", "internal-clean-web", "internal-process-web", "internal-optimize-web"]

[tasks.internal-run-web]
private = true
script = "basic-http-server web"

[tasks.run-web]
dependencies = ["build-web", "internal-run-web"]

[tasks.run-desktop]
script = "cargo run --features desktop --bin kg-std"
